=== pyvideo/data/.schemas/video.json
{
  "$schema":"http://json-schema.org/draft-07/schema#",
  "description":"The schema for a video record in pyvideo/data",
  "properties":{
    "alias":{
      "description":"[Deprecated] Legacy path to video on pyvideo.org",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "category":{
      "description":"[Deprecated] Category of video. This is duplicated by category files and is thus depriciated in video files.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "copyright_text":{
      "description":"Copyright license for video or link to copyright information.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "description":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "duration":{
      "description":"Duration of video (in seconds)",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "id":{
      "description":"ID for video. Must be unique amongst all videos if present.",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "language":{
      "description":"ISO 639-3 language code of spoken language used in video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "quality_notes":{
      "description":"Notes on quality of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "recorded":{
      "description":"ISO 8601 Date on which video was recorded (YYYY-MM-DD[Thh:mm:ss[+hh:mm]])",
      "anyOf": [
        {"type": "null"},
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}([+-][0-9]{2}:[0-9]{2})?)?$"
        }]
    },
    "related_urls":{
      "description":"Array of related resources' URLs.",
      "items":{
        "description":"URL of resource related to video.",
        "anyOf": [{
          "type": "string",
          "format":"uri"
        }, {
          "type": "object",
          "required": ["label", "url"],
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "label": {
              "type": "string"
            }
          }
        }]
      },
      "type":"array",
      "uniqueItems":true
    },
    "slug":{
      "description":"Web-safe slug for video. Must be unique amongst other videos in same category",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "speakers":{
      "description":"Ordered array of speakers in video.",
      "items":{
        "description":"Speaker name",
        "type":"string"
      },
      "type":"array",
      "uniqueItems":true
    },
    "summary":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "tags":{
      "description":"Array of tags describing video",
      "items":{
        "description":"Tag describing video",
        "type":"string",
        "minLength": 1
      },
      "type": "array",
      "uniqueItems":true
    },
    "thumbnail_url":{
      "description":"URL to thumbnail for video",
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "title":{
      "description":"Title of video",
      "type":"string"
    },
    "videos":{
      "description":"Array of video locations and types",
      "items":{
        "description":"A video location and type",
        "properties":{
          "type":{
            "description":"File type of video at associated location",
            "type":"string"
          },
          "url":{
            "description":"URL for video",
            "format":"uri",
            "type":"string"
          },
          "length":{
            "description":"[Deprecated] Size of video (in bytes). Please use 'size' instead.",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          },
          "size":{
            "description":"Size of video (in bytes)",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          }
        },
        "required":[
          "type",
          "url"
        ],
        "type":"object"
      },
      "type":"array",
      "uniqueItems":true,
      "minItems": 1
    }
  },
  "required":[
    "description",
    "speakers",
    "recorded",
    "title",
    "videos"
  ],
  "additionalProperties": false,
  "title":"Video",
  "type":"object"
}

=== pyvideo/data/pycon-us-2021/videos/tutorial-mike-muller-functional-python.json
{
  "copyright_text": null,
  "description": "I will use a JupyterLab for the tutorial because it makes a very good teaching tool. You are welcome to use the setup you prefer, i.e editor, IDE, REPL. If you also like to use a JupyterLab, I recommend conda for easy installation. Similarly to virtualenv, conda allows creating isolated environments but allows binary installs for all platforms.\n\nThere are two ways to install Jupyter via conda:\n\n1. Use Minconda. This is a small install and (after you installed it)\nyou can use the command conda to create an environment:\nconda create -n pycon2021py39 python=3.9\nNow you can change into this environment:\nconda activate pycon2021py39. The prompt should change to (pycon2021py39).\nNow you can install JupyterLab: conda install jupyterlab.\n\n2. Install Anaconda and you are ready to go if you don't mind installing\nlots of packages from the scientific field.\n\n3. Install the dependencies:\n* Jupyter Lab 2 conda install jupyterlab\n* more_itertools conda more_itertools\n* toolz conda install toolz\n\n4. Hint: You do all this in one command:\nconda create -n pycon2021py39 python=3.9 jupyterlab more-itertools toolz\n\nYou can create a comparable setup with virtual environments and pip, if you prefer.\n\nWORKING WITCH CONDA ENVIRONMENTS\nAfter creating a new environment, the system might still work with some stale settings. Even when the command which tells you that you are using an executable from your environment, this might actually not be the case. If you see strange behavior using a command line tool in your environment, use hash -r and try again.",
  "duration": 8874,
  "language": "eng",
  "recorded": "2021-05-14",
  "related_urls": [
    {
      "label": "Conference schedule",
      "url": "https://us.pycon.org/2021/schedule/"
    }
  ],
  "speakers": [
    "Mike M\u00fcller"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi_webp/8w1mqprAPaI/maxresdefault.webp",
  "title": "Functional Python",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=8w1mqprAPaI"
    }
  ]
}

=== pyvideo/data/pydata-seattle-2023/videos/goyal-ramakrishnan-enterprise-grade-full-stack-ml-platform-pydata-seattle-2023.json
{
  "description": "www.pydata.org\n\nThere is a pressing need for tools and workflows that meet data scientists where they are: how to enable an organization of data scientists, who may not have formal training as software engineers, to build and deploy end-to-end machine learning workflows and applications independently.\n\nWe wanted to provide the best possible user experience for data scientists, allowing them to focus on the parts of the ML stack where they can deliver the most value (such as modeling using their favorite off-the-shelf libraries) while providing secure & robust built-in solutions for the underlying infrastructure (including data, compute, orchestration, and versioning). In this talk, we discuss the problem space, our enterprise-scale challenges at Dell, and the approach we took to solving it with Metaflow, the open-source ML platform developed at Netflix, & Outerbounds.\n\nPyData is an educational program of NumFOCUS, a 501(c)3 non-profit organization in the United States. PyData provides a forum for the international community of users and developers of data analysis tools to share ideas and learn from each other. The global PyData network promotes discussion of best practices, new approaches, and emerging technologies for data management, processing, analytics, and visualization. PyData communities approach data science using many languages, including (but not limited to) Python, Julia, and R. \n\nPyData conferences aim to be accessible and community-driven, with novice to advanced level presentations. PyData tutorials and talks bring attendees the latest project features along with cutting-edge use cases.\n\n00:00 Welcome!\n00:10 Help us add time stamps or captions to this video! See the description for details.\n\nWant to help add timestamps to our YouTube videos to help with discoverability? Find out more here: https://github.com/numfocus/YouTubeVideoTimestamps",
  "duration": 2145,
  "language": "eng",
  "recorded": "2023-04-26",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://pydata.org/seattle2023/"
    },
    {
      "label": "https://github.com/numfocus/YouTubeVideoTimestamps",
      "url": "https://github.com/numfocus/YouTubeVideoTimestamps"
    }
  ],
  "speakers": [
    "TODO"
  ],
  "tags": [
    "Education",
    "Julia",
    "NumFOCUS",
    "Opensource",
    "PyData",
    "Python",
    "Tutorial",
    "coding",
    "how to program",
    "learn",
    "learn to code",
    "python 3",
    "scientific programming",
    "software"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/dJCBlzDuLb0/maxresdefault.jpg",
  "title": "Goyal & Ramakrishnan - Enterprise-grade Full Stack ML Platform | PyData Seattle 2023",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=dJCBlzDuLb0"
    }
  ]
}

=== pyvideo/data/pydata-paris-2024/videos/hendrik-makait-geoscience-at-massive-scale-pydata-paris-2024.json
{
  "description": "When scaling geoscience workloads to large datasets, many scientists and developers reach for Dask, a library for distributed computing that plugs seamlessly into Xarray and offers an Array API that wraps NumPy. Featuring a distributed environment capable of running your workload on large clusters, Dask promises to make it easy to scale from prototyping on your laptop to analyzing petabyte-scale datasets.\n\nDask has been the de-facto standard for scaling geoscience, but it hasn\u2019t entirely lived up to its promise of operating effortlessly at massive scale. This comes up in a few ways: \n- Correctly chunking your dataset has a significant impact on Dask\u2019s ability to scale \n- Workers accidentally run out of memory due to: \n  - Data being loaded too eagerly\n  - Rechunking\n  - Unmanaged memory\n\nOver the last few months, Dask has addressed many of those pains and continues to do so through:\n- Improvements to its scheduling algorithms\n- A faster and more memory-stable method for rechunking\n- First-of-its-kind logical optimization layer for a distributed array framework (ongoing)\n\nJoin us as we dive into real-world geoscience workloads, exploring how Dask empowers scientists and developers to run their analyses at massive scale. Discover the impact of improvements made to Dask, ongoing challenges, and future plans for making it truly effortless to scale from your laptop to the cloud.\n\nwww.pydata.org\n\nPyData is an educational program of NumFOCUS, a 501(c)3 non-profit organization in the United States. PyData provides a forum for the international community of users and developers of data analysis tools to share ideas and learn from each other. The global PyData network promotes discussion of best practices, new approaches, and emerging technologies for data management, processing, analytics, and visualization. PyData communities approach data science using many languages, including (but not limited to) Python, Julia, and R. \n\nPyData conferences aim to be accessible and community-driven, with novice to advanced level presentations. PyData tutorials and talks bring attendees the latest project features along with cutting-edge use cases.\n\n00:00 Welcome!\n00:10 Help us add time stamps or captions to this video! See the description for details.\n\nWant to help add timestamps to our YouTube videos to help with discoverability? Find out more here: https://github.com/numfocus/YouTubeVideoTimestamps",
  "duration": 1810,
  "language": "eng",
  "recorded": "2024-09-25",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://pydata.org/paris2024"
    },
    {
      "label": "https://github.com/numfocus/YouTubeVideoTimestamps",
      "url": "https://github.com/numfocus/YouTubeVideoTimestamps"
    }
  ],
  "speakers": [
    "TODO"
  ],
  "tags": [
    "Education",
    "Julia",
    "NumFOCUS",
    "Opensource",
    "PyData",
    "Python",
    "Tutorial",
    "coding",
    "how to program",
    "learn",
    "learn to code",
    "python 3",
    "scientific programming",
    "software"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/UOpNhItJNv8/sddefault.jpg",
  "title": "Hendrik Makait - Geoscience at Massive Scale | PyData Paris 2024",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=UOpNhItJNv8"
    }
  ]
}

=== pyvideo/data/pycon-tw-2023/videos/the-snake-of-theseus-pablo-galindo-salgado-keynote-ji-diao-yan-jiang.json
{
    "description": "PyCon Taiwan 2023\uff5cKeynote \u57fa\u8abf\u6f14\u8b1b\uff5cDay 1, 10:30\u201311:30\n\n\ud83e\ude84 \u8aaa\u660e Description \ud83e\ude84\nAs Python keeps evolving and attracts an ever-growing community with unique perspectives, steering council members and core developers face the enthralling challenge of preserving Python's fundamental identity. In this talk, we embark on a journey, exploring how Python retains its essence while evolving, accommodating new features, and embracing diverse viewpoints. From balancing innovation and compatibility, to navigating the maze of language design, we will discuss what fortifies Python against change and how we prepare to make complicated decisions\u00a0that may change the language forever.\n\n\n\n\ud83d\ude80 \u8b1b\u8005\u4ecb\u7d39 About Speaker - Pablo\u00a0Galindo\u00a0Salgado \ud83d\ude80\nPablo Galindo Salgado works in the Python Infrastructure team at the Software Infrastructure department at Bloomberg L.P. He is a CPython core developer and a Theoretical Physicist specializing in general relativity and black hole physics. He is currently serving on the Python Steering Council and he is the release manager for Python 3.10 and 3.11. He has also a cat but he does not code.\n\n\nFollow \u201cPyCon Taiwan\u201d\n\u2b50\ufe0f Official Website: https://tw.pycon.org\n\u2b50\ufe0f Facebook: https://www.facebook.com/pycontw\n\u2b50\ufe0f Instagram: https://www.instagram.com/pycontw\n\u2b50\ufe0f Twitter: https://twitter.com/PyConTW\n\u2b50\ufe0f LinkedIn: https://www.linkedin.com/company/pycontw\n\u2b50\ufe0f Blogger: https://conf.python.tw/",
    "speakers": [
        "Pablo Galindo Salgado"
    ],
    "recorded": "2023-09-02",
    "title": "The snake of Theseus\uff5cPablo Galindo Salgado\uff5cKeynote \u57fa\u8abf\u6f14\u8b1b\uff5cPyCon Taiwan 2023",
    "thumbnail_url": "https://i.ytimg.com/vi/0C4eKA5DXFs/hqdefault.jpg",
    "videos": [
        {
            "type": "youtube",
            "url": "https://www.youtube.com/watch?v=0C4eKA5DXFs"
        }
    ]
}

=== pyvideo/data/pydata-berlin-2023/videos/theodore-meynard-mlops-in-practice-our-journey-from-batch-to-real-time-inference.json
{
  "description": "I will present the challenges we encountered while migrating an ML model from batch to real-time predictions and how we handled them. In particular, I will focus on the design decisions and open-source tools we built to test the code, data and models as part of the CI/CD pipeline and enable us to ship fast with confidence.\n\nSlide: https://drive.google.com/file/d/1FzP3KEpimIah67WUI_HQksdHGDWFR6gW/view",
  "duration": 2079,
  "language": "eng",
  "recorded": "2023-04-17",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://2023.pycon.de/"
    },
    {
      "label": "https://drive.google.com/file/d/1FzP3KEpimIah67WUI_HQksdHGDWFR6gW/view",
      "url": "https://drive.google.com/file/d/1FzP3KEpimIah67WUI_HQksdHGDWFR6gW/view"
    }
  ],
  "speakers": [
    "TODO"
  ],
  "tags": [
    "Education",
    "Julia",
    "NumFOCUS",
    "Opensource",
    "PyData",
    "Python",
    "Tutorial",
    "coding",
    "how to program",
    "learn",
    "learn to code",
    "python 3",
    "scientific programming",
    "software"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/gvBaADatX9Y/maxresdefault.jpg",
  "title": "Theodore Meynard: MLOps in practice - our journey from batch to real-time inference",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=gvBaADatX9Y"
    }
  ]
}

=== pyvideo/data/pycon-ar-2020/videos/pyconar-2020-behave-para-entender-al-usuario.json
{
  "description": "Behave para Entender al Usuario",
  "duration": 1297,
  "language": "eng",
  "recorded": "2020-11-16",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://eventos.python.org.ar/events/pyconar2020/"
    }
  ],
  "speakers": [
    "Mar√≠a Camila Guerrero Giraldo"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/Ks7eLJJJhkk/maxresdefault.jpg",
  "title": "Behave para Entender al Usuario",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=Ks7eLJJJhkk"
    }
  ]
}

=== pyvideo/data/europython-2024/videos/an-alternative-view-on-the-openapi-documentation-maxim-danilov.json
{
  "description": "[EuroPython 2024 \u2014 South Hall 2B on 2024-07-11]\n\n\rAn alternative view on the OpenAPI documentation. by Maxim Danilov\n\rhttps://ep2024.europython.eu/session/an-alternative-view-on-the-openapi-documentation\n\n\rDocumenting Python project endpoints is a real challenge in API development. Poor readability, versioning, and lack of authentication information - this all reduce the usability of existing OpenAPI documentation. The different libraries offers us a good start for autogenerated OpenAPI documentation for our endpoints, but in this talk we will discuss an alternative way to auto generated documentation for our APIs.\n\n\n\r---\n\rThis work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License: https://creativecommons.org/licenses/by-nc-sa/4.0/",
  "duration": 1872,
  "language": "eng",
  "recorded": "2024-07-08",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://ep2024.europython.eu/"
    },
    {
      "label": "https://ep2024.europython.eu/session/an-alternative-view-on-the-openapi-documentation",
      "url": "https://ep2024.europython.eu/session/an-alternative-view-on-the-openapi-documentation"
    },
    {
      "label": "https://creativecommons.org/licenses/by-nc-sa/4.0/",
      "url": "https://creativecommons.org/licenses/by-nc-sa/4.0/"
    }
  ],
  "speakers": [
    "Maxim Danilov"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/EJ0rJ8TMmqU/maxresdefault.jpg",
  "title": "An alternative view on the OpenAPI documentation.",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=EJ0rJ8TMmqU"
    }
  ]
}

=== pyvideo/data/pydata-global-2020/videos/ben-fowler-chelsey-meise-openingtheblackbox-pydata-global-2020.json
{
  "description": "Talk \nData scientists have likely heard that machine learning models are \u2018black boxes\u2019 and not interpretable. This notion, once formerly true, is no longer correct. In this talk, the modelers at Southeast Toyota Finance will focus on model-agnostic interpretability techniques. We\u2019ll provide an end-to-end example of the experimentation process of modeling combined with interpretability techniques.\n\n\nwww.pydata.org\r\n\r\nPyData is an educational program of NumFOCUS, a 501(c)3 non-profit organization in the United States. PyData provides a forum for the international community of users and developers of data analysis tools to share ideas and learn from each other. The global PyData network promotes discussion of best practices, new approaches, and emerging technologies for data management, processing, analytics, and visualization. PyData communities approach data science using many languages, including (but not limited to) Python, Julia, and R. \r\n\r\nPyData conferences aim to be accessible and community-driven, with novice to advanced level presentations. PyData tutorials and talks bring attendees the latest project features along with cutting-edge use cases. 00:00 Welcome!\n00:10 Help us add time stamps or captions to this video! See the description for details.\n\nWant to help add timestamps to our YouTube videos to help with discoverability? Find out more here: https://github.com/numfocus/YouTubeVideoTimestamps",
  "duration": 1711,
  "language": "eng",
  "recorded": "2020-11-11",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://pydataglobal.github.io/"
    },
    {
      "label": "https://github.com/numfocus/YouTubeVideoTimestamps",
      "url": "https://github.com/numfocus/YouTubeVideoTimestamps"
    }
  ],
  "speakers": [
    "Ben Fowler",
    "Chelsey Meise"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi_webp/8lwfGf7HAEc/maxresdefault.webp",
  "title": "OpeningTheBlackBox",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=8lwfGf7HAEc"
    }
  ]
}
