=== pyvideo/data/.schemas/video.json
{
  "$schema":"http://json-schema.org/draft-07/schema#",
  "description":"The schema for a video record in pyvideo/data",
  "properties":{
    "alias":{
      "description":"[Deprecated] Legacy path to video on pyvideo.org",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "category":{
      "description":"[Deprecated] Category of video. This is duplicated by category files and is thus depriciated in video files.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "copyright_text":{
      "description":"Copyright license for video or link to copyright information.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "description":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "duration":{
      "description":"Duration of video (in seconds)",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "id":{
      "description":"ID for video. Must be unique amongst all videos if present.",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "language":{
      "description":"ISO 639-3 language code of spoken language used in video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "quality_notes":{
      "description":"Notes on quality of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "recorded":{
      "description":"ISO 8601 Date on which video was recorded (YYYY-MM-DD[Thh:mm:ss[+hh:mm]])",
      "anyOf": [
        {"type": "null"},
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}([+-][0-9]{2}:[0-9]{2})?)?$"
        }]
    },
    "related_urls":{
      "description":"Array of related resources' URLs.",
      "items":{
        "description":"URL of resource related to video.",
        "anyOf": [{
          "type": "string",
          "format":"uri"
        }, {
          "type": "object",
          "required": ["label", "url"],
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "label": {
              "type": "string"
            }
          }
        }]
      },
      "type":"array",
      "uniqueItems":true
    },
    "slug":{
      "description":"Web-safe slug for video. Must be unique amongst other videos in same category",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "speakers":{
      "description":"Ordered array of speakers in video.",
      "items":{
        "description":"Speaker name",
        "type":"string"
      },
      "type":"array",
      "uniqueItems":true
    },
    "summary":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "tags":{
      "description":"Array of tags describing video",
      "items":{
        "description":"Tag describing video",
        "type":"string",
        "minLength": 1
      },
      "type": "array",
      "uniqueItems":true
    },
    "thumbnail_url":{
      "description":"URL to thumbnail for video",
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "title":{
      "description":"Title of video",
      "type":"string"
    },
    "videos":{
      "description":"Array of video locations and types",
      "items":{
        "description":"A video location and type",
        "properties":{
          "type":{
            "description":"File type of video at associated location",
            "type":"string"
          },
          "url":{
            "description":"URL for video",
            "format":"uri",
            "type":"string"
          },
          "length":{
            "description":"[Deprecated] Size of video (in bytes). Please use 'size' instead.",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          },
          "size":{
            "description":"Size of video (in bytes)",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          }
        },
        "required":[
          "type",
          "url"
        ],
        "type":"object"
      },
      "type":"array",
      "uniqueItems":true,
      "minItems": 1
    }
  },
  "required":[
    "description",
    "speakers",
    "recorded",
    "title",
    "videos"
  ],
  "additionalProperties": false,
  "title":"Video",
  "type":"object"
}

=== pyvideo/data/pytexas-2014/videos/case-study-using-git-to-manage-ui-derived-config.json
{
  "alias": "video/3156/case-study-using-git-to-manage-ui-derived-config",
  "category": "PyTexas 2014",
  "copyright_text": "CC-BY",
  "description": "Git is common choice for DVCS by software development teams. This case\nstudy describes a python system called ClicBank, that captures domain\nspecific UI entity definitions (in medical insurance industry) as XML\nfiles and manages changes in the configurations using open source Git\nmodules. This case study will describe the use cases driving this\ndesign, design choices, schema approach, implementation decisions,\npython modules, workspace/repository design, number of managed entities,\nGIT performance and status of project.\n",
  "duration": 3000,
  "id": 3156,
  "language": "eng",
  "quality_notes": "",
  "recorded": "2014-10-04",
  "slug": "case-study-using-git-to-manage-ui-derived-config",
  "speakers": [
    "Doug Matzke"
  ],
  "summary": "",
  "tags": [],
  "thumbnail_url": "https://archive.org/services/img/pyvideo_3156___Case_Study_Using_Git_to_manage_UI_derived_configur",
  "title": "Case Study: Using Git to manage UI derived configuration Elements",
  "videos": [
    {
      "type": "archive.org",
      "url": "https://archive.org/details/pyvideo_3156___Case_Study_Using_Git_to_manage_UI_derived_configur"
    },
    {
      "length": null,
      "type": "mp4",
      "url": "http://64966d3674e0a64d8f4a-47c94b14ef8e1f83d5390cdb0629c6ed.r53.cf2.rackcdn.com/pytexas-2014/3156_Case_Study_Using_Git_to_manage_UI_derived_configur.mp4"
    },
    {
      "length": 0,
      "type": "youtube",
      "url": "http://youtu.be/48fcIml0-_Y"
    }
  ]
}

=== pyvideo/data/scipy-2016/videos/3d-drawing-in-python-reviving-visual-scipy-2016-catherine-holloway.json
{
  "copyright_text": "Standard YouTube License",
  "description": "In 2000 David Scherer created Visual, a python package with a simple interface for drawing 3D objects to the screen. Visual abstracted away calls to OpenGL vertex drawing, textures, and transformations, and allowed primitive geometric objects to be placed on the screen in an intuitive manner. Visual was subsequently adopted by many researchers and university instructors, primarily in physics, to visualize scientific results and simulation assignments. The original Visual module used C++ to make OpenGL calls, and compatibility with Linux was never implemented. Python and OpenGL have come a long way in the past sixteen years, and now Visual can be made cross-platform by removing the C++ backend. I will present my attempt to re-implement Visual using pyglet, as well as demonstrate its API and usage in education and research visualization.",
  "duration": 1654,
  "language": "eng",
  "recorded": "2016-07-15",
  "related_urls": [],
  "slug": "3d-drawing-in-python-reviving-visual-scipy-2016-catherine-holloway",
  "speakers": [
    "Catherine Holloway"
  ],
  "tags": [
    "SciPy 2016"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/lrk6erM3mkI/maxresdefault.jpg",
  "title": "3D Drawing in Python: Reviving Visual",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=lrk6erM3mkI"
    }
  ]
}

=== pyvideo/data/writethedocs-na-2016/videos/csat-whats-that.json
{
  "description": "Betsy Roseberg\nhttp://lanyrd.com/2016/writethedocs/sfbztq/\nAs a tech writer, you care about two things: knowing your audience and delivering the most concise information possible to that audience. But how do you do that when your audience is incredibly specialized? What if the information you\u2019re presenting is rapidly changing? How can you be certain that your documentation is always relevant for that audience?\nTo answer all those questions, at New Relic we use CSAT (Customer Satisfaction) data. Our Docs team monitors CSAT comments and data for every single public-facing doc we own. We use that data to make dynamic decisions that affect our site and our docs work, influencing everything from quick doc fixes, giant rewrites, and our own site\u2019s functionality.\nEvery pertinent comment receives attention from at least one tech writer. Part of our code example is out of date? Fixed. There\u2019s a glitch on our site? We\u2019ll look into it. We list a version of Mongo that\u2019s outdated? Updated. By focusing on these comments, your audience is working with you to keep your documentation updated.\nWhat happens when a customer doesn\u2019t leave a comment, and just says the document wasn\u2019t helpful? We track that too. When docs have consistently negative feedback without constructive comments, we know that at least something in that doc needs work. When that happens, we work with SMEs to rewrite those docs and give them a little love. We polish \u2018em up and publish them again, tracking their data afterwards to make sure that they\u2019re indeed improved.\nAnd this doesn\u2019t just benefit the Docs team. We\u2019ve forwarded UI complaints to design, and disgruntled customer comments to Support. That\u2019s part of the beauty of CSAT: it\u2019s a direct line to all the customers looking for help with our products. With CSAT, our audience is helping us to curate the best possible information for all their needs.\nBut we\u2019re not stopping there. Soon, we\u2019ll be implementing OAuth for our CSAT data. Once that\u2019s enabled, we\u2019ll be able to see what specific products customers are using, what region they\u2019re in, what type of user permissions they have, and a ton of other stuff. We\u2019ll be positively swimming in audience connectedness from our CSAT, and with it, we\u2019ll know that our audience is understanding our concise information in the best way possible.",
  "recorded": "2016-05-22",
  "speakers": [
    "Betsy Roseberg"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/Nmx9_GZNZF8/hqdefault.jpg",
  "title": "CSAT - What\u2019s That?",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=Nmx9_GZNZF8"
    }
  ]
}

=== pyvideo/data/pydata-berlin-2023/videos/noa-tamir-how-are-we-managing-data-teams-management-irl.json
{
  "description": "The title \u201cData Scientist\u201d has been in use for 15 years now. We have been attending PyData conferences for over 10 years as well. The hype around data science and AI seems higher than ever before. But How are we managing?\n\nhttps://speakerdeck.com/noatmair/how-are-we-managing-data-teams-management-irl",
  "duration": 2765,
  "language": "eng",
  "recorded": "2023-04-17",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://2023.pycon.de/"
    },
    {
      "label": "https://speakerdeck.com/noatmair/how-are-we-managing-data-teams-management-irl",
      "url": "https://speakerdeck.com/noatmair/how-are-we-managing-data-teams-management-irl"
    }
  ],
  "speakers": [
    "TODO"
  ],
  "tags": [
    "Education",
    "Julia",
    "NumFOCUS",
    "Opensource",
    "PyData",
    "Python",
    "Tutorial",
    "coding",
    "how to program",
    "learn",
    "learn to code",
    "python 3",
    "scientific programming",
    "software"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/5oBMxhdO-Us/maxresdefault.jpg",
  "title": "Noa Tamir:  How Are We Managing? Data Teams Management IRL",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=5oBMxhdO-Us"
    }
  ]
}

=== pyvideo/data/pytexas-2013/videos/scraping-the-web-with-scrapy.json
{
  "description": "Dave has been developing in Django for 3 years in sunny Austin, TX, where he is an organizer for the Austin Web Python User Group. He worked for the Texas Tribune building data apps and contributing to the open source Armstrong CMS framework built on top of Django. He is now freelancing after his latest attempt at the startup game crashed. He enjoys shooting sports and barbecueing beef when he's not scraping ecommerce sites. The worst bet he's ever lost was when he was forced to retake the SAT at the age of 27 because he came in dead last in a fantasy football league.\n\nPython has great tools like Django and Flask for taking your database and turning it into html pages, but what if you want to take somebody else's html pages and build a database from them? Scrapy is a library for building web spiders that will simplify your web scraping tasks immensely. Friends don't let friends use raw urllib2.",
  "duration": 2749,
  "language": "eng",
  "recorded": "2013-08-16",
  "speakers": [
    "Dave McLain"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/eD8XVXLlUTE/hqdefault.jpg",
  "title": "Scraping the Web with Scrapy",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=eD8XVXLlUTE"
    }
  ]
}

=== pyvideo/data/python-barranquilla/videos/integra-un-asistente-personal-de-ia-generativa-en-tus-apps-sin-ser-un-experto-parte-2.json
{
  "description": "Esta es una continuaci\u00f3n de la charla https://pybaq.co/eventos/2024-09-05-integra-un-asistente-personal-de-ia-generativa-en-tus-apps-sin-ser-un-experto/\r\n\r\nEn esta sesi\u00f3n veremos como integrar asistentes personales generados por IA de forma f\u00e1cil en tus aplicaciones en Python, sin necesidad de experiencia previa, y como integrarlo a cualquier aplicaci\u00f3n a trav\u00e9s de APIs.\r\n\r\nNivel: Intermedio\r\nPonente: Elizbeth Fuentes\r\n\r\nEn mi rol de Especialista en An\u00e1lisis de Datos y Aprendizaje Autom\u00e1tico/Inteligencia Artificial (ML/AI), mi misi\u00f3n es simplificar conceptos complejos, traduci\u00e9ndolos a un lenguaje accesible para todos. Me dedico a crear soluciones innovadoras que enfrentan de forma eficaz los retos que surgen en el mundo real. A trav\u00e9s de mi participaci\u00f3n en conferencias y la creaci\u00f3n de recursos educativos, busco compartir mis conocimientos y experiencias con el fin de empoderar a los desarrolladores, ayud\u00e1ndoles a expandir sus habilidades y alcanzar sus objetivos profesionales.\n\nM\u00e1s info en https://pybaq.co/eventos/2024-10-09-integra-un-asistente-personal-de-ia-generativa-en-apps-sin-ser-experto-parte-2/",
  "duration": 3569,
  "language": "eng",
  "recorded": "2024-10-10",
  "related_urls": [
    {
      "label": "Website",
      "url": "https://pybaq.co/"
    },
    {
      "label": "https://pybaq.co/eventos/2024-09-05-integra-un-asistente-personal-de-ia-generativa-en-tus-apps-sin-ser-un-experto/\r",
      "url": "https://pybaq.co/eventos/2024-09-05-integra-un-asistente-personal-de-ia-generativa-en-tus-apps-sin-ser-un-experto/\r"
    },
    {
      "label": "https://pybaq.co/eventos/2024-10-09-integra-un-asistente-personal-de-ia-generativa-en-apps-sin-ser-experto-parte-2/",
      "url": "https://pybaq.co/eventos/2024-10-09-integra-un-asistente-personal-de-ia-generativa-en-apps-sin-ser-experto-parte-2/"
    }
  ],
  "speakers": [
    "TODO"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/I75sSA_KXsA/sddefault.jpg?v=66e850fa",
  "title": "Integra un asistente personal de IA generativa en tus apps sin ser un experto: Parte 2",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=I75sSA_KXsA"
    }
  ]
}

=== pyvideo/data/europython-2020/videos/kanianthra-chandy-iotpy-python-streams-agents-for-streaming-applications.json
{
  "copyright_text": "This video is licensed under the CC BY-NC-SA 3.0 license: https://creativecommons.org/licenses/by-nc-sa/3.0/\nPlease see our speaker release agreement for details: https://ep2020.europython.eu/events/speaker-release-agreement/\n",
  "description": "\"IoTPy: Python + Streams + Agents for Streaming Applications\nEuroPython 2020 - Talk - 2020-07-23 - Brian\nOnline\n\nBy Kanianthra Chandy\n\nSensors, social media, news feeds, webcams and other sources generate streams of data which are analyzed to control actuators, generate alerts, and feed displays. These applications process streams on onboard computers, such as the Raspberry Pi, connected directly to sensors, and send summarized information to the cloud for further processing. These applications have two characteristics: (1) Concurrency: The applications are concurrent using multiple threads to connect to sensors and actuators, shared memory across multiple processes on multicore machines and message passing for distributed systems spanning multiple computers. (2) Data Analysis: The applications use programs from a variety of libraries including those for signal processing, machine learning and natural language processing.\n\nDevelopers of streaming applications can use open-source software to deal with both characteristics. Concurrency: multiprocessing.Array can be used to construct shared-memory multiprocessing Python programs in multicore computers, and frameworks such as APMQ and Kafka can be used to build distributed applications. Data Analysis: A vast collection of open-source Python libraries can be used to analyze data in streams. Developers of streaming applications encounter an impedance mismatch between the software libraries that address these two characteristics. The next paragraph describes the mismatch and how IoTPy addresses it. \n\nPrograms in most software libraries apply a function to data, get results, and terminate execution. By contrast, streaming applications are perpetual processes that analyze endless streams of data. IoTPy helps developers: (1) build non-terminating streaming applications by harnessing conventional terminating programs from Python\u2019s huge base of libraries and (2) create multithreaded, multicore and distributed Python applications by simply connecting streams to each other.\n\nhttps://www.AssembleSoftware.com\n\n\n\nLicense: This video is licensed under the CC BY-NC-SA 3.0 license: https://creativecommons.org/licenses/by-nc-sa/3.0/\nPlease see our speaker release agreement for details: https://ep2020.europython.eu/events/speaker-release-agreement/\n\n\"",
  "duration": 1610,
  "language": "eng",
  "recorded": "2020-07-23",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://ep2020.europython.eu/"
    },
    {
      "label": "https://ep2020.europython.eu/events/speaker-release-agreement/",
      "url": "https://ep2020.europython.eu/events/speaker-release-agreement/"
    },
    {
      "label": "https://creativecommons.org/licenses/by-nc-sa/3.0/",
      "url": "https://creativecommons.org/licenses/by-nc-sa/3.0/"
    },
    {
      "label": "https://www.AssembleSoftware.com",
      "url": "https://www.AssembleSoftware.com"
    }
  ],
  "speakers": [
    "Kanianthra Chandy"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/AYkxrCaFG6s/sddefault.jpg",
  "title": "IoTPy: Python + Streams + Agents for Streaming Applications",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=AYkxrCaFG6s"
    }
  ]
}

=== pyvideo/data/pytorchconf-2023/videos/lightning-talk-uplink-interference-optimizer-how-to-optimize-a-cellular-network-oscar-gonzalez.json
{
  "description": "Lightning Talk: Uplink Interference Optimizer, How to Optimize a Cellular Network in a Single Shot with GNNs - Oscar Llorente Gonzalez, Ericsson\n\nOptimizing cellular networks has been a very difficult task for a long time. In these networks multiple problematic issues appear and the high number of parameters and variables to optimize makes it a difficult problem even for radio experts. Here an optimizer for a cellular network is presented, the Uplink Interference Optimizer. Specifically, the uplink interference problem (degradation of the signal transmitted from a user terminal to a base station) will be solved by constructing a model that predicts a variable that reflects the interference level (SINR) and then optimizing the parameters of the cellular network, based on the model that has been built, to reduce it. That way, we achieve the optimization in a single step, improving previous solutions based on RL that must iterate over the real cellular network for several weeks. The simulator model will be based on Graph Neural Networks (constructed with PyTorch and PyTorch Geometric), allowing us to consider the neighborhood of a cell to make a prediction, which enhances the prediction accuracy over all older models. Then, any algorithm could be run to improve the parameters based on the simulator model we have constructed.",
  "duration": 726,
  "language": "eng",
  "recorded": "2023-10-16",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://pytorch.org/event/pytorch-conference-2023/"
    }
  ],
  "speakers": [
    "TODO"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/c96UxNyHuRo/maxresdefault.jpg",
  "title": "Lightning Talk: Uplink Interference Optimizer, How to Optimize a Cellular Network...- Oscar Gonzalez",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=c96UxNyHuRo"
    }
  ]
}
