=== pyvideo/data/.schemas/video.json
{
  "$schema":"http://json-schema.org/draft-07/schema#",
  "description":"The schema for a video record in pyvideo/data",
  "properties":{
    "alias":{
      "description":"[Deprecated] Legacy path to video on pyvideo.org",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "category":{
      "description":"[Deprecated] Category of video. This is duplicated by category files and is thus depriciated in video files.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "copyright_text":{
      "description":"Copyright license for video or link to copyright information.",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "description":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "duration":{
      "description":"Duration of video (in seconds)",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "id":{
      "description":"ID for video. Must be unique amongst all videos if present.",
      "anyOf": [{"type": "null"}, {"type": "integer"}]
    },
    "language":{
      "description":"ISO 639-3 language code of spoken language used in video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "quality_notes":{
      "description":"Notes on quality of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "recorded":{
      "description":"ISO 8601 Date on which video was recorded (YYYY-MM-DD[Thh:mm:ss[+hh:mm]])",
      "anyOf": [
        {"type": "null"},
        {
          "type": "string",
          "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}(T[0-9]{2}:[0-9]{2}:[0-9]{2}([+-][0-9]{2}:[0-9]{2})?)?$"
        }]
    },
    "related_urls":{
      "description":"Array of related resources' URLs.",
      "items":{
        "description":"URL of resource related to video.",
        "anyOf": [{
          "type": "string",
          "format":"uri"
        }, {
          "type": "object",
          "required": ["label", "url"],
          "properties": {
            "url": {
              "type": "string",
              "format": "uri"
            },
            "label": {
              "type": "string"
            }
          }
        }]
      },
      "type":"array",
      "uniqueItems":true
    },
    "slug":{
      "description":"Web-safe slug for video. Must be unique amongst other videos in same category",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "speakers":{
      "description":"Ordered array of speakers in video.",
      "items":{
        "description":"Speaker name",
        "type":"string"
      },
      "type":"array",
      "uniqueItems":true
    },
    "summary":{
      "description":"reStructuredText or plain text description of video",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "tags":{
      "description":"Array of tags describing video",
      "items":{
        "description":"Tag describing video",
        "type":"string",
        "minLength": 1
      },
      "type": "array",
      "uniqueItems":true
    },
    "thumbnail_url":{
      "description":"URL to thumbnail for video",
      "format":"uri",
      "anyOf": [{"type": "null"}, {"type": "string"}]
    },
    "title":{
      "description":"Title of video",
      "type":"string"
    },
    "videos":{
      "description":"Array of video locations and types",
      "items":{
        "description":"A video location and type",
        "properties":{
          "type":{
            "description":"File type of video at associated location",
            "type":"string"
          },
          "url":{
            "description":"URL for video",
            "format":"uri",
            "type":"string"
          },
          "length":{
            "description":"[Deprecated] Size of video (in bytes). Please use 'size' instead.",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          },
          "size":{
            "description":"Size of video (in bytes)",
            "anyOf": [{"type": "null"}, {"type": "integer"}]
          }
        },
        "required":[
          "type",
          "url"
        ],
        "type":"object"
      },
      "type":"array",
      "uniqueItems":true,
      "minItems": 1
    }
  },
  "required":[
    "description",
    "speakers",
    "recorded",
    "title",
    "videos"
  ],
  "additionalProperties": false,
  "title":"Video",
  "type":"object"
}

=== pyvideo/data/pydata-amsterdam-2024/videos/vasiliy-kaminskiy-how-research-teams-can-deliver-higher-quality-insights-faster-pydata.json
{
  "description": "www.pydata.org\n\nDelivering high-quality insights swiftly is crucial for research teams aiming for excellence. The key to achieving this lies in operational efficiency across all stages of the research workflow.\n\nPyData is an educational program of NumFOCUS, a 501(c)3 non-profit organization in the United States. PyData provides a forum for the international community of users and developers of data analysis tools to share ideas and learn from each other. The global PyData network promotes discussion of best practices, new approaches, and emerging technologies for data management, processing, analytics, and visualization. PyData communities approach data science using many languages, including (but not limited to) Python, Julia, and R. \n\nPyData conferences aim to be accessible and community-driven, with novice to advanced level presentations. PyData tutorials and talks bring attendees the latest project features along with cutting-edge use cases.\n\n00:00 Welcome!\n00:10 Help us add time stamps or captions to this video! See the description for details.\n\nWant to help add timestamps to our YouTube videos to help with discoverability? Find out more here: https://github.com/numfocus/YouTubeVideoTimestamps",
  "duration": 2189,
  "language": "eng",
  "recorded": "2024-09-18",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://web.archive.org/web/20240822042916/https://amsterdam.pydata.org/"
    },
    {
      "label": "https://github.com/numfocus/YouTubeVideoTimestamps",
      "url": "https://github.com/numfocus/YouTubeVideoTimestamps"
    }
  ],
  "speakers": [
    "Vasiliy Kaminskiy"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/GEVcX-OM1hg/maxresdefault.jpg",
  "title": "How Research Teams Can Deliver Higher-Quality Insights Faster",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=GEVcX-OM1hg"
    }
  ]
}

=== pyvideo/data/pydata-delhi-2019/videos/how-i-used-data-visualization-in-my-quest-for-the-perfect-wine-by-pranav-suri.json
{
  "description": "For many, wine is a taste acquired over many years; others use data. In\nthis talk, I recite the story of how I uncovered the constituents of a\ngood wine using Data Visualization while discussing the nuances of\nExploratory Data Analysis (EDA) \u2013 the process of taking the first glance\nat data.\n\nIdea Behind The Talk\n^^^^^^^^^^^^^^^^^^^^\n\nWith the rise of tools allowing for smooth implementation of powerful\nalgorithms, it is tempting to skip EDA. However, **EDA is just as\nimportant as any part of a data project; if you don't know your data\nwell enough, you can end up doing very shallow work** , i.e., inaccurate\nmodels, choosing wrong variables, inefficient use of resources, or all\nof the above. Sometimes, EDA uncovers more than what the confirmatory\nstudy would've done otherwise.\n\nExploratory Data Analysis is what one should do when first encountering\na dataset. However, it's not a one-off process: there are setbacks,\nmultiple iterations, and the process sets the tone for a more formal\nanalysis of data in hand. **With a story-like format, the presentation\nmentions the setbacks one faces when performing a real data study.**\n\n**The motivation behind creating this talk is to impart the idea of\nExploratory Data Analysis, and how Data Visualizations help uncover\npatterns (not limited to the findings of the wine study). Moreover, I\nbelieve the format of a sharing a real story with the idea of \"how to\nreach and infer from a specific plot\" would help the audience understand\ndata visualization better than talking about syntactic sugar of a\nparticular visualization library. Moreover, the ideas can be further\ngeneralized to any other visualization library.**\n\nOutline of the Talk\n^^^^^^^^^^^^^^^^^^^\n\n-  History of Wine & Data Science\n-  Introduction to Exploratory Data Analysis (EDA)\n-  Why Data Visualization? \u2013 Anscombe's Quartet\n-  The Grammar of Graphics: Why I used ggplot2?\n\nWine Project: Finding Constituents of Good Red & White Wines\n''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''\n\n-  About the Project & How to Replicate It?\n-  How to Quantify \u2018Artistic\u2019 Measures?\n-  Principles of Data Visualization to Uncover Patterns\n-  Inspecting Data Using Univariate, Bivariate & Multivariate Plots\n\nAspects of EDA Not Used In the Wine Project\n'''''''''''''''''''''''''''''''''''''''''''\n\n-  How to Prepare Your Dataset? \u2013 Data Aggregation\n-  How to Remove Outliers Using Data Visualization\n-  How to Decide the Best Fit During EDA\n-  When to Transform Variables\n",
  "duration": 1171,
  "language": "eng",
  "recorded": "2019-08-04",
  "speakers": [
    "Pranav Suri"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/T54uP8imSaM/hqdefault.jpg",
  "title": "How I Used Data Visualization in My Quest for the Perfect Wine",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=T54uP8imSaM"
    }
  ]
}

=== pyvideo/data/pydata-global-2021/videos/a-first-step-from-ad-hoc-sql-to-scalable-etl-martin-wanjiru-pydata-global-2021.json
{
  "description": "A First Step From Ad-hoc Sql to Scalable ETL\nSpeaker: Martin Wanjiru\n\nSummary\nSoftware engineers design tables to capture transactions, which are not ideal for querying. On the other hand, Data Scientists and Analysts require limitless view of business data, which is only achievable using long and complex SQL queries. This creates the need to have a separate analytics database with a multidimensional database structure. This talk discusses a solution for this problem.\n\nDescription\n\u201cHey team, I have these two dashboards on the number of sales and they don\u2019t agree. Why is this the case, and which is correct? Can this be fixed before my 10 am meeting with investors?\u201d or \u201cI want to create a data science model to categorize our customers based on their repayment trends and their adherence to their PTP (promise to pay) plans, so that the operations team can put more effort on the customers less likely to pay on time and less on the promising ones - where can I get this data?\u201d, these are the kind of reporting problems we faced on a daily. We lacked a single source of truth. Most of our SQL business logic was spread across our tools, from 400+ lines of complex SQL queries creating materialized views on the production database (something the Engineering team did not take kindly) to other queries living in our BI Tools (redash and Tableau). If the business logic slightly changed, It was very difficult to update all our queries. Furthermore, debugging was painful! All these challenges prompted us to have a separate database for analytics. We opted for an ELT process. We got a tool to replicate data from the production database to the data warehouse. We then started using DBT to do SQL transformation. DBT does most of the work for us - it determines the execution order of the models (SQL statements) and created objects in our warehouse. It also allows us to test our models, to ensure that the defined business logic is not violated. These models live in a version control, making it easy to track changes we do. We also have a CI/CD tool that we use to run the models hourly. This set up has improved the way we report.The time spent to gather and clean data to be consumed by our data science models has also significantly reduced.\n\nMartin Wanjiru's Bio\nI am a data enthusiast, currently working as a Data Analyst at Apollo Agriculture. My day to day work involves doing ELT processes in our data warehouse, transforming and modeling data using DBT, and making dashboards in our BI tools (redash and Tableau)\nGitHub: https://github.com/NdiranguMartin/\nLinkedIn: https://www.linkedin.com/in/martin-wanjiru-98414111a/\nWebsite: https://ndirangumartin.netlify.app//\n\nPyData Global 2021\nWebsite: https://pydata.org/global2021/\nLinkedIn: https://www.linkedin.com/company/pydata-global\nTwitter: https://twitter.com/PyData\n\nwww.pydata.org\n\nPyData is an educational program of NumFOCUS, a 501(c)3 non-profit organization in the United States. PyData provides a forum for the international community of users and developers of data analysis tools to share ideas and learn from each other. The global PyData network promotes discussion of best practices, new approaches, and emerging technologies for data management, processing, analytics, and visualization. PyData communities approach data science using many languages, including (but not limited to) Python, Julia, and R. \n\nPyData conferences aim to be accessible and community-driven, with novice to advanced level presentations. PyData tutorials and talks bring attendees the latest project features along with cutting-edge use cases.\n\n00:00 Welcome!\n00:10 Help us add time stamps or captions to this video! See the description for details.\n\nWant to help add timestamps to our YouTube videos to help with discoverability? Find out more here: https://github.com/numfocus/YouTubeVideoTimestamps",
  "duration": 1434,
  "language": "eng",
  "recorded": "2021-10-28",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://pydata.org/global2021/"
    },
    {
      "label": "https://www.linkedin.com/company/pydata-global",
      "url": "https://www.linkedin.com/company/pydata-global"
    },
    {
      "label": "https://github.com/numfocus/YouTubeVideoTimestamps",
      "url": "https://github.com/numfocus/YouTubeVideoTimestamps"
    },
    {
      "label": "https://twitter.com/PyData",
      "url": "https://twitter.com/PyData"
    },
    {
      "label": "https://github.com/NdiranguMartin/",
      "url": "https://github.com/NdiranguMartin/"
    },
    {
      "label": "https://ndirangumartin.netlify.app//",
      "url": "https://ndirangumartin.netlify.app//"
    },
    {
      "label": "https://www.linkedin.com/in/martin-wanjiru-98414111a/",
      "url": "https://www.linkedin.com/in/martin-wanjiru-98414111a/"
    },
    {
      "label": "https://pydata.org/global2021/",
      "url": "https://pydata.org/global2021/"
    }
  ],
  "speakers": [
    "Martin Wanjiru"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/EPiSBzVnz_E/maxresdefault.jpg",
  "title": "A First Step From Ad-hoc Sql to Scalable ETL",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=EPiSBzVnz_E"
    }
  ]
}

=== pyvideo/data/djangocon-2015/videos/wagtail-yet-another-django-cms-by-tom-dyson.json
{
  "category": "DjangoCon 2015",
  "copyright_text": "",
  "description": "",
  "duration": 1717,
  "id": 4867,
  "language": "eng",
  "quality_notes": "",
  "recorded": "2015-09-21",
  "related_urls": [
    "http://amara.org/v/HH7a/"
  ],
  "slug": "wagtail-yet-another-django-cms-by-tom-dyson",
  "speakers": [
    "Tom Dyson"
  ],
  "summary": "Wagtail - Yet Another Django CMS by Tom Dyson\n\nWagtail was launched in February 2014, shortly after its first\nimplementation for the Royal College of Art. It has been\nenthusiastically received by Django developers around the world, and now\npowers sites for small businesses, UN agencies, and global brands in\ntech, political and entertainment sectors. Tom will explain why his\nagency decided to build a new CMS, share some lessons learned in running\na growing open source project, and outline Wagtail's roadmap to version\n2 and beyond.\n\nHelp us caption & translate this video!\n\nhttp://amara.org/v/HH7a/\n",
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/6j0NVq6g4FE/maxresdefault.jpg",
  "title": "Wagtail - Yet Another Django CMS",
  "videos": [
    {
      "length": 0,
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=6j0NVq6g4FE"
    }
  ]
}

=== pyvideo/data/pycon-us-2022/videos/keynote-naomi-ceder.json
{
  "copyright_text": "CC BY",
  "description": "Naomi Ceder earned a Ph.D in Classics several decades ago, but switched from ancient human languages to computer languages sometime in the last century. Since 2001, she has been learning, teaching, writing about, and using Python.\n\nShe has attended every PyCon since the first one in 2003 and was one of the originators of the Poster Session, the Education Summit, the Intro to Sprints sessions, the PyCon Charlas, and the Hatchery.\n\nAn elected fellow of the Python Software Foundation, Naomi is the immediate past chair of its board of directors. She is also co-founder of Trans*Code and speaks internationally about Python as well as community, inclusion, and diversity in technology in general.\n\nThe author of The Quick Python Book and the Explore Python Fundamentals project series, she has also done corporate training in Python. In her spare time she enjoys sketching, knitting, and deep philosophical conversations with her dog.",
  "duration": 2225,
  "language": "eng",
  "recorded": "2022-04-27",
  "related_urls": [
    {
      "label": "Conference schedule",
      "url": "https://us.pycon.org/2022/schedule/"
    },
    {
      "label": "About Keynote Speakers",
      "url": "https://us.pycon.org/2022/about/keynote-speakers/#naomi"
    }
  ],
  "speakers": [
    "Naomi Ceder"
  ],
  "tags": [
    "Keynote"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/sFmwGQu0cQU/hqdefault.jpg",
  "title": "Naomi Ceder",
  "videos": [
    {
      "length": 2225,
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=sFmwGQu0cQU"
    }
  ]
}

=== pyvideo/data/pycon-italia-2022/videos/don-t-rely-on-discipline.json
{
  "copyright_text": null,
  "description": "Don\u2019t rely on discipline - PyCon Italia 2022\n\nIn the programming field we often rely on discipline. We expect from\nourselves and from others that we will not introduce bugs and cause\nproblems. That we will use the libraries and APIs as they are intended.\nThat we will not cut corners.\n\nSadly, tales from the industry tell us otherwise. This talk explores why\nwe should not rely on discipline as a bouncer against bugs, and what to\nrely on instead.\n\nSlides:\n\nSpeaker: Nejc Zupan\n",
  "duration": 1869,
  "language": "eng",
  "recorded": "2022-06-03",
  "speakers": [
    "Nejc Zupan"
  ],
  "tags": [
    "clean code",
    "static analysis",
    "testing"
  ],
  "thumbnail_url": "https://i.ytimg.com/vi/DOivZctKoYo/maxresdefault.jpg",
  "title": "Don't rely on discipline",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=DOivZctKoYo"
    }
  ]
}

=== pyvideo/data/europython-2020/videos/gunjan-dewan-developing-a-match-making-algorithm-between-customers-and-go-jek-products.json
{
  "copyright_text": "This video is licensed under the CC BY-NC-SA 3.0 license: https://creativecommons.org/licenses/by-nc-sa/3.0/\nPlease see our speaker release agreement for details: https://ep2020.europython.eu/events/speaker-release-agreement/\n",
  "description": "\"Developing a match-making algorithm between customers and Go-Jek products!\nEuroPython 2020 - Poster session - 2020-07-24 - Poster 1\nOnline\n\nBy Gunjan Dewan\n\nGoJek has millions of monthly active users in Indonesia across our 20+ products and services. A major problem we faced was targeting these customers with promos and vouchers that were relevant to them. We developed a generalized model that takes into account the transaction history of users and gives a ranked list of our services that they are most likely to use next. From here on, we are able to determine the vouchers that we can target these customers with.\nIn this poster, I will be presenting our process while developing the model, the challenges we faced during the time, how we used PySpark to tackle these challenges and the impact it had on our conversion rates.\n\n\n\nLicense: This video is licensed under the CC BY-NC-SA 3.0 license: https://creativecommons.org/licenses/by-nc-sa/3.0/\nPlease see our speaker release agreement for details: https://ep2020.europython.eu/events/speaker-release-agreement/\n\n\"",
  "duration": 1745,
  "language": "eng",
  "recorded": "2020-07-23",
  "related_urls": [
    {
      "label": "Conference Website",
      "url": "https://ep2020.europython.eu/"
    },
    {
      "label": "https://ep2020.europython.eu/events/speaker-release-agreement/",
      "url": "https://ep2020.europython.eu/events/speaker-release-agreement/"
    },
    {
      "label": "https://creativecommons.org/licenses/by-nc-sa/3.0/",
      "url": "https://creativecommons.org/licenses/by-nc-sa/3.0/"
    }
  ],
  "speakers": [
    "Gunjan Dewan"
  ],
  "tags": [],
  "thumbnail_url": "https://i.ytimg.com/vi/m8-9Q8gI5eQ/sddefault.jpg",
  "title": "Developing a match-making algorithm between customers and Go-Jek products!",
  "videos": [
    {
      "type": "youtube",
      "url": "https://www.youtube.com/watch?v=m8-9Q8gI5eQ"
    }
  ]
}

=== pyvideo/data/pyohio-2016/videos/for-those-about-to-mock-i-salute-you.json
{
  "description": "Testing python applications can be confusing, and leave you in a daze about what the proper way to test is when creating an API or accessing a remote service. Let's explore the testing world with a gentle introduction to unittest, py.test, mock, gabbi, and betamax. We'll learn how to isolate our tests from databases, APIs and third party libraries.",
  "duration": 3000,
  "recorded": "2016-07-31",
  "speakers": [
    "Jason Myers"
  ],
  "title": "For those about to Mock I salute you!",
  "videos": [
    {
      "type": "youtube",
      "url": "http://youtu.be/lJux36gTlxY"
    }
  ]
}
